site_name: Scala Design
copyright: Copyright &copy; 2021-2022 mikusugar
theme:
  language: zh
  favicon: img/logo.png
  name: material
  features:
    - navigation.tabs
  logo: img/logo.png
repo_url: https://github.com/MikuSugar/scala-design
repo_name: MikuSugar/scala-design
site_description:  scala-design
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - 主页: index.md